language: java
jdk:
- oraclejdk8

after_success:
  - mvn clean test jacoco:report 
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - fernando.dodino@gmail.com
      - grisoliarodrigo@gmail.com
    on_success: [change] # default: change | [always|never|change]
    on_failure: [always] # default: always | [always|never|change]
